@echo off
cmpdf ../system/algorithm.cm
cmpdf ../system/assert.cm
cmpdf ../system/bitset.cm
cmpdf ../system/bytestream.cm
cmpdf ../system/charclass.cm
cmpdf ../system/codeformatter.cm
cmpdf ../system/concept.cm
cmpdf ../system/condvar.cm
cmpdf ../system/console.cm
cmpdf ../system/convert.cm
cmpdf ../system/date.cm
cmpdf ../system/eh.cm
cmpdf ../system/exception.cm
cmpdf ../system/exec.cm
cmpdf ../system/filestream.cm
cmpdf ../system/function.cm
cmpdf ../system/fwdlist.cm
cmpdf ../system/hashmap.cm
cmpdf ../system/hashset.cm
cmpdf ../system/hashtable.cm
cmpdf ../system/iterator.cm
cmpdf ../system/limits.cm
cmpdf ../system/linkedlist.cm
cmpdf ../system/list.cm
cmpdf ../system/map.cm
cmpdf ../system/mt.cm
cmpdf ../system/mtx.cm
cmpdf ../system/mutex.cm
cmpdf ../system/nupo.cm
cmpdf ../system/pair.cm
cmpdf ../system/path.cm
cmpdf ../system/ptr.cm
cmpdf ../system/queue.cm
cmpdf ../system/rbtree.cm
cmpdf ../system/rvalue.cm
cmpdf ../system/set.cm
cmpdf ../system/sha1.cm
cmpdf ../system/sha256.cm
cmpdf ../system/sha512.cm
cmpdf ../system/stack.cm
cmpdf ../system/stream.cm
cmpdf ../system/string.cm
cmpdf ../system/stringstream.cm
cmpdf ../system/textutil.cm
cmpdf ../system/thread.cm
cmpdf ../system/time.cm
cmpdf ../system/tracer.cm
cmpdf ../system/uhuge.cm
cmpdf ../system/utility.cm
